//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityModel
    {
        public int ID { get; set; }
        public string ActivityName { get; set; }
        public Nullable<int> ActivityPrice { get; set; }
        public Nullable<int> ActivityNoOfPeople { get; set; }
        public string ActivityType { get; set; }
        public string ActivityLocation { get; set; }
        public string isBooked { get; set; }
        public string isSaved { get; set; }
    }
}
